### PR TITLE
Adding Raspberry Pi 4 UART pins

### PR DESCRIPTION
**Pull request by mys721tx**
Adds Raspberry Pi 4 UART pins.

### CODE REVIEW

**Comment by Myriachan** [comment]
Raspberry is spelled Paspberry in one of your new comments.

Which set of ports applies to which UART?

**Comment by mys721tx** [comment]
I was planning on adding the pin definitions for Raspberry Pi 4 but that is pending on #322.

The following are the pin usages for each UART. UART0 and miniUART can use pins in other banks.

| UART          | TX | RX | CTS | RTS |
|---------------|----|----|-----|-----|
|UART0/miniUART | 14 | 15 |     |     |
|UART0/miniUART | 32 | 33 |     |     |
|UART0/miniUART | 36 | 37 |     |     |
|UART2          | 0  | 1  | 2   | 3   |
|UART3          | 4  | 5  | 6   | 7   |
|UART4          | 8  | 9  | 10  | 11  |
|UART5          | 12 | 13 | 14  | 15  |

**Comment by Gadgetoid** [comment]
I'm going to need to tackle #322 so we can move onwards and upwards with Pi4 specific features, but for the time being I think this change is useful. Thank you.

**Comment by lurch** [comment]
I don't think it affects this PR, as the relevant GPIOs aren't available on the Pi's 40pin GPIO header, but note that there's a slight error in the table above. According to https://elinux.org/RPi_BCM2711_GPIOs UART1 **isn't** available on GPIOs 36-39 inclusive.

Also, this PR lists RTS and CTS as `direction: both` but https://en.wikipedia.org/wiki/RS-232#Data_and_control_signals says that RTS is 'out' (the same as TxD) and CTS is 'in' (the same as RxD) ? :shrug:

**Comment by lurch** [comment]
Looks like this PR has been merged, but doesn't seem to be visible at https://pinout.xyz/pinout/uart yet?

**Pull request merged**
