### PR TITLE
Fix pinout of button Y on unicorn hat mini

### PR DESCRIPTION
**Pull request by please-insert-username-here**

### CODE REVIEW

**Comment by lurch** [comment]
Hmmm? The **GPIO** numbers shown on https://pinout.xyz/pinout/unicorn_hat_mini (5, 6, 16, 20) seem to match up with what https://github.com/pimoroni/unicornhatmini-python/blob/master/library/unicornhatmini/__init__.py says? :man_shrugging:

**Comment by Gadgetoid** [comment]
And... yet... https://github.com/pimoroni/unicornhatmini-python/blob/master/examples/buttons.py

https://github.com/pimoroni/unicornhatmini-python/blob/6fbeed56433a7474de1005a5ef1f44b194051be8/examples/buttons.py#L20-L28

In many cases we moved away from the i2s pin so we wouldn't break support for audio boards, but I don't recall if this was one of the boards we did that with. Might have to dig up the schematic. Right now the buttons example and library disagreeing is... odd.

**Comment by Gadgetoid** [comment]
This does - in fact - match the schematic. The library is wrong :grimacing: - or perhaps outdated since some boards got a respin to change the Y button.

**Comment by lurch** [comment]
Pesky hardware not matching up with what the software is telling it to do... :rofl:

**Pull request merged**
