### PR TITLE
Voice Hat: "I2C"->"I2S" and add Pin 38

### PR DESCRIPTION
**Pull request by combs**
my first PR for this project, so please let me know if there's anything I should update!

Thanks!

### CODE REVIEW

**Comment by combs** [comment]
P.S., here is a source showing that both I2S pins are used by the HAT:
https://aiyprojects.withgoogle.com/voice-v1/#makers-guide--gpio-pinout-and-expansions

**Comment by Gadgetoid** [comment]
Thank you!

**Comment by lurch** [comment]
@Gadgetoid I've only just noticed that this PR edits one file in `src/de/` and one in `src/en/`, so I guess that might cause some confusion when trying to update all the translations to be consistent? :dizzy_face:  (i.e. hopefully the change here won't get overwritten)

**Comment by combs** [comment]
oh that's silly on my part. Sorry about that. I'd be happy to fix it in a new PR, coming soon.

**Pull request merged**
