### PR TITLE
Add pi-top/pi-topCEED hub boards

### PR DESCRIPTION
**Pull request by m-roberts**

### CODE REVIEW

**Comment by RogueM** [comment]
as I commented when you originally submitted the Pi-Top PULSE, the boards must be able to be fitted onto a Pi header - sorry this is a site-wide policy!

**Comment by recantha** [comment]
Ummm. Hang on... The pi-topPULSE _can_ be fitted onto a Pi header! I know because that's how I've been playing around with one.

**Comment by m-roberts** [comment]
This is for the hub - pi-topPULSE got merged in.

**Comment by recantha** [comment]
Oh, in that case, I can see their point.

**Comment by recantha** [comment]
(recantha looks as stupid as he feels. It's been a bad day ;-) )

**Pull request closed without merging**
