### PR TITLE
Added RoboHat, PZM Shim and PiStop

### PR DESCRIPTION
**Pull request by 4tronix**

### CODE REVIEW

**Comment by RogueM** [comment]
cheers. It would really help if you had good top-down images... we can scourge your urls to see if there is something suitable but in an ideal world overlays and accompanying board image would be supplied together.

... if you aren't confident with that aspect then don't worry, we can fill that gap, but this will typically add significantly add lead time to publication of the boards.

**Comment by Gadgetoid** [comment]
@4tronix had emailed some over to me for the last batch of boards which were damn near perfect, so I don't mind doing the same for these boards.

Do we have a procedure for submitting original photos for us to run through our template? Seems like it may or may not be a good fit for GitHub.

**Comment by RogueM** [comment]
there is a template .png in the draft section of the repo. I guess it's not the ideal way, but at leat it gives users a sense of size required, and the possibility to submit a (as close as can be) board image.

**Comment by RogueM** [comment]
note that the picon-zero tweaks included in this PR has been merged into the existing overlay, so that one can be ignored (if you end up finalising this one).

I have also removed pin 4 from the pin definition, for consistency and uncluttering... until a better system comes along, it should be assumed that pin2 and pin4 are bridged (though admitedly there is at leat one exception - blink).

**Comment by RogueM** [comment]
oh, I see the previous 2 other boards that are live were resummitted too... not sure what has changed. type should be 'motor' though, corrected in the (pending) overlays, to avoid duplication of filtering categories.

**Comment by RogueM** [comment]
@4tronix , for existing board modifications, the preferred method would be to touch up the md files in the overlay folder (in the /src/en section). the draft 'step' was created mostly for new submission, that often crashing the renderer in the past, due to formatting, requiring us to debug those issues before being able to push site updates out.

I'll take care of those 2 boards now though, it's just a FYI for future requirements.

**Comment by lurch** [comment]
> I have also removed pin 4 from the pin definition, for consistency and uncluttering...

TBH I'm not sure I see the need for that? If a board _uses_ pins 2 and 4, what's wrong with showing them both on pinout.xyz ?

**Comment by RogueM** [comment]
users asking (on our forums) whether they need to connect both ;-)

**Comment by lurch** [comment]
Well isn't it the same answer as for multiple ground pins? "You could, but it (probably) shouldn't hurt if you only connect one" ? You don't 'block' multiple ground pins.
And I guess it's _theoretically_ possible for an addon-board to use each of pins 2 and 4 to power a different part of their circuitry? ;)

**Comment by RogueM** [comment]
well... that is essentially why all ground and power pins disappeared for an extended period of time. It's a can of worms that puts a lot of demands on the site, which is seen responsible for any inaccuracies (with a couple of complains transferred wrongly to Pimoroni in the past, which is a byproduct of me and Phil working there).

but, hey, it's an open source implementation, so if it's deem the best way forward, someone is willing to amend (and confirm accuracy!) for all existing boards, and being on call to answer queries 24/7, then sure, I'm fine with _any_ implementation ;-)

**Comment by lurch** [comment]
> someone is willing to amend all existing boards

Well, I know who's been editing the existing boards to take *out* pin 4... ;-)

Perhaps there should be a notice on http://pinout.xyz/ clarifying that it's an independent project and saying that it has nothing to do with Pimoroni. I don't visit the pimoroni forums myself, but I'd expect any threads about pinout.xyz on there to just point to https://github.com/Gadgetoid/Pinout.xyz/issues ?

And perhaps there should be a disclaimer at the bottom of each 'board' page (e.g. http://pinout.xyz/pinout/wifi_pants ), saying that any errors lie entirely with the individual contributors, and pinout.xyz makes no claims as to accuracy of the displayed information?

I know people aren't keen on disclaimers, but better that than you being incorrectly blamed for wrong information :-/

> and being on call to answer queries 24/7, then sure, I'm fine with _any_ implementation ;-)

Heh heh :laughing:

**Comment by 4tronix** [comment]
Already sent images last week except for the motor shim

**Comment by 4tronix** [comment]
OK thanks for explaining. And thanks for all the hard work guys. It's a great site!

**Pull request merged**
