### PR TITLE
New 14 boards translated to Spanish

### PR DESCRIPTION
**Pull request by IkerGarcia**
I am almost new to this, why I am getting always the "Can't automatically merge" message? Also all the latests commits, that are supposed to be a closed PR appear as commits (accumulative) when I try to PR.

### CODE REVIEW

**Comment by RogueM** [comment]
are you rebasing your fork regularly? I suspect you do since you got the latest boards... it seems that blinkt in es is in conflict. That board was amended a few days ago (adding the install stuff, which we do on all translations at once).

**Comment by RogueM** [comment]
hum, that file, for some reason, your PR is trying to remove it from the repo, so check your fork, it has got to be missing there?

Normally, if you adjust your fork it should automatically resolve the conflict. If not, I'll do it manually.

**Comment by IkerGarcia** [comment]
I think that the problem is that, being a noob, I did several PR and then tried to rebase instead of rebasing regularly. I don't know why while rebasing, blinkt was removed.

Added blinkt manually, think it should be fine know. Thank you for the explanation!

**Comment by RogueM** [comment]
cheers, looks good!

there's a few other files with untranslated context btw, our system isn't as streamlined as we'd wish and the html templates boost their own set of language specific strings, sorry about that :(

https://github.com/Gadgetoid/Pinout.xyz/blob/master/src/es/template/boards.html
https://github.com/Gadgetoid/Pinout.xyz/blob/master/src/es/template/layout.html

there's also a few here that are likely 'broken' Spanish I'm sure:
https://github.com/Gadgetoid/Pinout.xyz/blob/master/src/es/settings.yaml

**Comment by IkerGarcia** [comment]
I will check them and translate in a while, as I need to be more careful not to break the html code.

**Comment by RogueM** [comment]
if you'd like I can do a file tomorrow with just the strings. It is not a big job to extract or reinsert after the fact for me. either way there's no great rush, just wasn't sure where to find the untranslated strings that appear at http://es.pinout.com came from.

**Comment by IkerGarcia** [comment]
That is a great idea, it will be easier to translate without messing anything. Thank you!

**Comment by RogueM** [comment]
sorry, lack of time lately. Plus we are doing changes that probably will affect what strings need translating (or rather adding a few to the list), so when that's done I'll create a list and assign an 'issue' to you to let you know (*I think* that works).

... for now I'll merge those in.

**Pull request merged**
