### PR TITLE
Update ZeroBorg image

### PR DESCRIPTION
**Pull request by tuftii**
Added the most up to date picture of a ZeroBorg board as they are now with terminals, I2C connectors, IR receiver and DCDC.

### CODE REVIEW

**Comment by lurch** [comment]
Do those new features mean that the "new ZeroBorg" has a different pinout to the "old ZeroBorg"? If so, perhaps there should be a separate page?

**Comment by Gadgetoid** [comment]
Thank you! The slightly not-quite-perfectly-top-down photo makes my eye twitch a little bit, but a correct photo is better than an incorrect one none the less.

**Comment by lurch** [comment]
image

**Comment by tuftii** [comment]
I prefer @lurch 's image, can I rollback please?

(Sorry, I tried to get as on top as I could :cry:)

**Pull request merged**
