### PR TITLE
Add pi-topPULSE board

### PR DESCRIPTION
**Pull request by m-roberts**

### CODE REVIEW

**Comment by RogueM** [comment]
please read our contribution section in the README... we do not accept overlays published directly to the tree the renderer uses to produces the HTML files. Instead they should be submitted as part of the `draft` folder.

**Comment by RogueM** [comment]
oh, sorry, I had a look at the product included... I'm sorry but we only include boards that can be plugged directly onto the Pi header as part of pinout :/

**Comment by m-roberts** [comment]
Sorry - I read that as well! I will take care of that now :)

**Comment by m-roberts** [comment]
@RogueM - is this correct?

**Comment by m-roberts** [comment]
Closed due to no longer being appropriate to merge from Master.

**Pull request closed without merging**
