### PR TITLE
Add @modmypi's JamHat.

### PR DESCRIPTION
**Pull request by tuftii**
The JamHat is a @modmypi hat featuring 6 LEDs, 2 buttons and a buzzer.

Added here for discussion to make sure it's an appropriate board to add to Pinout.xyz :smile:

### CODE REVIEW

**Comment by tuftii** [comment]
:100: need to expand the description to include some more info!

**Comment by Gadgetoid** [comment]
Thank you! I'll review it ASAP.

**Comment by tuftii** [comment]
Ok. Made a few little updates, I don't want to fill the page too much! Cheers Phill :smile:

**Comment by Gadgetoid** [comment]
Thank you. Fantastic job with the image! Saved me a step :D

**Pull request merged**
