### PR TITLE
French Translation Batch 1

### PR DESCRIPTION
**Pull request by smileyn64**
Hi,
I have translated in French the following cards:
- RTC Pi Zero
- 4tronix-picon-zero
- ab-1-wire-plus
- ab-1-wire-zero
- ab-adc-differential-pi 
- ab-adc-pi-plus
- ab-adc-pi-zero
- ab-adcdac-pi-zero

I also updated the string in the fr/settings.yaml to be in line with the english one.

Finally I updated the fr/index.md as per english version.

I’m currently translating the rest of the card available in the English site, I think I will regularly post by batch of 8-10 cards translated.

Cheers,
Smileyn

### CODE REVIEW

**Comment by smileyn64** [comment]
Just saw that I can continue to commit to the pull request, maybe you want me to finish the full translation before merging with the master ?
If yes I will rename the pull "French Translation" only

cheers

**Comment by RogueM** [comment]
no, it's fine, we merge PR when we get to it. I'll take a look tonight... feel free to push anything you'd like in this PR, an when this one is merged in, create a new one if you have any additions.

et merci beacoup pour ton aide!

**Comment by smileyn64** [comment]
Just added a note about how to fix some preview issues after
modification and building.
Error occurring:
- New Card not showing but accessible by URL
- String translated not showing good everywhere.

Purging the browser cache do the trick, only image and file cache
requires to be purged.

and ... De rien ! c'était le moins que je puisse faire, ce site m'a bien aidé !

**Comment by Gadgetoid** [comment]
This is wonderful. Thank you!

**Pull request merged**
