### PR TITLE
new mdb2pi-hat

### PR DESCRIPTION
**Pull request by mmame**

### CODE REVIEW

**Comment by Gadgetoid** [comment]
Thanks for your submission!

I'm having trouble building Pinout with this overlay, I haven't got time to look into it in depth tonight, but my gut feeling says the overly greedy regex responsible for grabbing the Yaml chunk at the top of the page is consuming down to line 68 and thus trying to parse the content as Yaml:

```text
yaml.scanner.ScannerError: while scanning a simple key
  in "<string>", line 48, column 1:
    -->
    ^
could not found expected ':'
  in "<string>", line 49, column 1:
    # MDB2Pi HAT
    ^
```

If you could replace the `-->` on line 68 with something else, I'd be happy to give it another try.

Ideally everything after, and including, `## Configuration` should be dropped, since Pinout.xyz isn't intended to be a comprehensive documentation for boards- the page structure just isn't there, so this content will- at best- look pretty awful, even if its inclusion is well intentioned and useful.

Looking into better supporting and encouraging more comprehensive documentation is probably a discussion for an Issue.

**Comment by mmame** [comment]
I've dropped the Configuration section and added a link instead...

**Comment by Gadgetoid** [comment]
Brilliant, thank you!

**Comment by mmame** [comment]
Looks like an error occured with board image - it isn't shown:
https://pinout.xyz/resources/boards/mdb2pi-hat.png results in a 404

**Comment by Gadgetoid** [comment]
This is quite probably because I'm stupid and forgot to publish the images!

**Comment by Gadgetoid** [comment]
Fixed!

**Comment by mmame** [comment]
Thanks 😀

Am 19.12.2017 16:16 schrieb "Philip Howard" <notifications@github.com>:

**Pull request merged**
