### PR TITLE
Added zeroseg

### PR DESCRIPTION
**Pull request by geek2003**
I have added the pi hut's zero seg board.

Let me know if there are any problems

### CODE REVIEW

**Comment by geek2003** [comment]
I have also now added motozero again from the pi hut

**Comment by geek2003** [comment]
Now navio2 aswell

**Comment by geek2003** [comment]
And another of my specialities the adafruit joy bonnet

**Comment by RogueM** [comment]
cheers! be careful with capitalisations of the tags in the YAM header though, right now it's tricky business to avoid duplication of the `formfactor` and `type`. Great job though, and certainly appreciated!

**Pull request merged**
