### PR TITLE
Product updated.

### PR DESCRIPTION
**Pull request by saucompeng**
Our Sixfab product updated to V2. Old version retired.

### CODE REVIEW

**Comment by lurch** [comment]
Hmmm, but perhaps the pinout-info of the old version would still be useful for owners of the existing V1 board? (unless of course no V1 boards were ever sold?)

**Comment by saucompeng** [comment]
Ok I will add new, not update existing

4 Eyl 2018 Sal 19:53 tarihinde Andrew Scheller <notifications@github.com>
şunu yazdı:

**Comment by saucompeng** [comment]
New version added.

**Comment by Gadgetoid** [comment]
Published! https://pinout.xyz/pinout/3g4glte_base_shield_v2

**Pull request merged**
