### PR TITLE
Attempt Adafruit LCD

### PR DESCRIPTION
**Pull request by geek2003**
Have I done this right. It is the adafruit 16x2 LCD raspberry pi add on board

### CODE REVIEW

**Comment by geek2003** [comment]
Ok thanks for the feedback. Will remember for next time!

**Comment by Gadgetoid** [comment]
When you submit a Pull Request it doesn't snapshot that moment in time, but keeps track of the branch you're requesting a pull from. If you go back to your copy of this repository and make those changes- even through the GitHub web UI- they will be updated here. Give it a try!

**Comment by geek2003** [comment]
I will give this a try later! I did not realise this was the case. Once this one is uploaded adafruit arcade bonnet will be hot on it's tail

**Comment by geek2003** [comment]
Okay I have added the I2C info and fixed the issue with the apostrophes! 
Hope all is good now? Sorry for the delay I had to wait until I got home from school!

**Comment by geek2003** [comment]
Just remembered about the motor hat as an issue. Do you want me to do that as a pull request as well?

**Comment by geek2003** [comment]
3 new adafruit boards!!!!!!!!

**Comment by geek2003** [comment]
Ok they are all the adafruit boards I can find. Let me know if you can find any more.

**Comment by Gadgetoid** [comment]
Oooh, another quirk of your submissions- the YAML header all seems to be indented by one space. This actually gets treated as text by the parser and throws off the processing so the keys are `' name'` instead of `'name'`. You'll need to watch out for that in future!

**Comment by Gadgetoid** [comment]
For future references:

* I tweaked most images, lazily, to fit the template positioning and dimensions- they may need redoing
* Removed an erroneous (physical pin 11) PCM/I2S pin from Arcade Bonnet
* Changed instances of `mode:i2c` to `mode: i2c`. YAML is fussy and breaks othwerise.
* Removed indenting
* Minor text corrections and tweaks, nothing outrageous
* Renamed all files to `<manufacturer>-board-name-<type>` where possible

I'll have to see if I can remove the requirement for an `image` setting in the Yaml, since the image name should always be the same as the markdown filename, so it seems redundant!

Otherwise, great stuff. Keep 'em coming.

Note: I haven't pushed the boards live yet- I'll poke @RogueM to build it and have a glance over for sanity, plus discuss some things like I2S and DPI where it looks like it would be easier if pins got their name automatically when given a `mode`, where a matching protocol is available. But should be live soooon!

**Pull request merged**
