### PR TITLE
Request to add 3 new audio shields from raspiaudio.com

### PR DESCRIPTION
**Pull request by roscop13**
Changes to be committed:
	new file:   draft/boards/audioplus.png
	new file:   draft/boards/audioplus_speakerplus.png
	new file:   draft/boards/audioplus_speakerplus_micplus.png

	new file:   draft/overlay/audioplus.md
	new file:   draft/overlay/audioplus_speakerplus.md
	new file:   draft/overlay/audioplus_speakerplus_micplus.md

### CODE REVIEW

**Comment by Gadgetoid** [comment]
Thank you!

I've fixed a couple of typos and some formatting and changed the text so it flows better in English, could you have a look at the drafts in https://github.com/Gadgetoid/Pinout.xyz/tree/master/draft/overlay and make sure I haven't broken anything?

**Comment by roscop13** [comment]
I checked and it looks good to me, thanks for your review.

Kind regards,
Olivier

Le sam. 12 mai 2018 à 12:00, Philip Howard <notifications@github.com> a
écrit :

**Comment by lurch** [comment]
I've just noticed that these are showing up under https://pinout.xyz/boards#formFactor=Undefined
However looking at the pictures they appear to be pHAT form-factor?

**Comment by lurch** [comment]
Also, `extention` should be spelled `extension` :wink:

**Pull request merged**
