### PR TITLE
Sixfab Cellular Application Hat pinout added

### PR DESCRIPTION
**Pull request by saucompeng**

### CODE REVIEW

**Comment by Gadgetoid** [comment]
I'll look into this as soon as I can- however for future reference don't submit the overlay as "published" IE: you don't need to edit any of the settings.yaml files or copy it into multiple language folders.

The overlays should go in draft/overlays and images in draft/boards - https://github.com/Gadgetoid/Pinout.xyz/tree/master/draft

**Comment by saucompeng** [comment]
I put overlay file and picture into draft folder then ./publish and make. After compile I added new files then push. What is wrong ?

**Comment by Gadgetoid** [comment]
It's not a huge deal, but I usually run ./publish and make to test the overlay is okay and make any appropriate tweaks before merging and pushing live. Merging unpublished also ensures you don't conflict the settings.yaml files- which has happened here.

**Comment by saucompeng** [comment]
What should I do now?

**Comment by Gadgetoid** [comment]
Don't worry- I'm working on it!

**Comment by Gadgetoid** [comment]
Sorted! Will get this pushed live tonight.

**Comment by saucompeng** [comment]
Thanks you too

**Pull request merged**
