### PR TITLE
New boards

### PR DESCRIPTION
**Pull request by francesco-vannini**
Added Flicks
Added Bright Pi
Added GertVGA 666
Amended pins for Amp Zero
Amended Pi PoE details and renamed to keep in line with others

### CODE REVIEW

**Comment by RogueM** [comment]
thanks. Can you test the pages and resubmit however as I can tell right away they will crash the renderer. Also, bright-pi falls outside the scope of the site, so sorry, that one will be discarded.

**Comment by RogueM** [comment]
to clarify, you should build and preview using:

```bash
./draft/publish gertvga-666
make serve LANG=de
```

And then open: http://127.0.0.1:5000 in your browser to check the result, if the renderer does not crash. Right now I think most/all of it because of the power declaration, if nothing else. You should only assign the pins, i.e there should be nothing additional on the same line as 'power', this is a long deprecated way to describe power that you have there (well, a mix of old and new).

**Comment by RogueM** [comment]
for got to add... once you have finalised your overlays use:

```bash
./draft/unpublish myboard
```
(this will file the overlay back into the draft folder, ready for review)

**Comment by RogueM** [comment]
I have now added those instructions to:
https://github.com/Gadgetoid/Pinout.xyz/blob/master/README.md#contributing

(they used to be there but further down the page, for translators benefit)

**Comment by francesco-vannini** [comment]
Shame about the Bright Pi but I understand.

I wasn't sure about that then I read the instructions in the template:
_DESIRABLE

pincount: the header pin count, typically 26 or 40 but shims/custom boards are acceptable.
eeprom: whether the board includes an eeprom (required by 'HAT' specs!).
power: the supply logic required by the board. Valid values are 'external', '3v3', '5v' and '3v3,5v'.
i2c: if the board uses i2c, a list of the bus address(es) and device(s) identification.__

also I saw that on the side you tend to use the information somehow by stating
_Needs 5v and 3v3 power_
in the details of the board's page

I'll test without the power information and see if it all works.

Also it would be nice to have a list of values for type and eeprom. Is eeprom just yes, no or "setup" is also allowed? Is "setup" meaning DT blob?

**Comment by francesco-vannini** [comment]
So I have tried publishing the gertvga-666 by first copying the md under draft/overlay and the png under draft/boards
I have removed "no" near "power:" but I get
_>> Rendering: src/en/translate/gertvga-666.md
Traceback (most recent call last):
  File "./generate-html.py", line 566, in <module>
    link = (overlay['page_url'], overlay['name'])
TypeError: 'NoneType' object has no attribute '__getitem__'
Makefile:15: recipe for target 'html' failed
make: *** [html] Error 1_
What am I doing wrong?

**Comment by francesco-vannini** [comment]
@RogueM before I resubmit got a second to address the above?

**Comment by RogueM** [comment]
I'm going to have a look at that board and see what else I can spot... unfortunately, the renderer is not explicit about faults in the overlays, unless we specifically code it to handle particular cases.

And, yes, apology, the 'template' is grossly outdated, I'm going to update it now and add extra info that would be useful to specify there.

**Comment by RogueM** [comment]
there were a number of issues, besides specifying a generic power value, though none crashed for me. I have corrected them and published the board, but FYI:

- there is no mode for VGA, or DPI for that matter, so all relevant pins descriptions were changed to 'name'.
- parentheses were included in the name label, while pinout uses parentheses around all labels

**Comment by francesco-vannini** [comment]
@RogueM I am really sorry, I thought I had done a better job this time. Every time I am sure things are fine and then I'll miss something like "mode" instead of "name"! I looked at it and was sure it spelt "name", go figure, getting old-er I guess. Thanks for this.
About the eeprom. Is eeprom just yes, no or "setup" is also allowed? Is "setup" meaning DT blob?

**Comment by RogueM** [comment]
yes, `setup` means auto-configuration via Device Tree. It means those pins should be connected... I/we have it on our TODO list to interrelate that field value to highlight bcm0-1 on the pinout, eventually.

For now we ask that they are omitted from the `pin` declaration though, even in cases where that would be necessary (well, an overlay can be loaded manually so DT blob technically does not mean those pins have to be connected, though that is the easiest option, obviously).

**Comment by francesco-vannini** [comment]
makes sense. I guess the majority of our boards should really just say "yes" instead of "setup" as only a bunch really have DT blobs. I'll amend it some time in the future, it's not crucial at the minute. Thanks @RogueM , is there anything else I need to do before things get published?

**Comment by RogueM** [comment]
you need to submit those boards as drafts, not in the main tree. I can sort out the ones we are happy to publish.

**Comment by francesco-vannini** [comment]
what an idiot, I did, didn't I? Please if you can go ahead with fixing this too that I'd appreciate. Sorry again.

**Comment by francesco-vannini** [comment]
Hey @RogueM I see the GertVGA made it to the panel, any troubles with the others? I had made slight changes to the Pi PoE and JustBoom Amp Zero a part from introducing the Flicks. I know you didn't want to include the Bright Pi so I know that won't be published so I imagine the same should be for the Flick Large.

**Comment by RogueM** [comment]
yes, correct Flick large will get the axe. You need to move the files in your PR to the draft folder - as soon as that is done I'll merge and check they are OK to publish.

... if easier I can kill this PR for you to resubmit in a cleaner fashion?

**Comment by francesco-vannini** [comment]
Well let's close this one and I'll create a new one just for what's left to do.

**Pull request closed without merging**
