### PR TITLE
adding icubex pishield

### PR DESCRIPTION
**Pull request by johnty**
adding pinout specs for icubex pishield. let me know if i've done everything correctly. thanks!

### CODE REVIEW

**Comment by RogueM** [comment]
I'll check now. For future requests, it is preferred if they are filed as a draft, where they can't inadvertedly trip the process of publishing content live.

**Comment by RogueM** [comment]
I have a query about your board. What devices are expected on the I2C bus? or do you just provide O2C breakouts via 4 landings, for users to attach external sensors? ... I suspect the later, in which case BCM2-3 should not be part of the pinout.

**Comment by johnty** [comment]
Hi there,

Thanks for the quick response!

Yes, your assumption is correct. I guess it makes more sense to take it out as there are no devices sitting on the I2C bus by default.

Johnty

**Comment by RogueM** [comment]
np. yes, we don't normally document broken out pins, particularly i2c, since they don't necessarily represent a conflict in term of combining boards.

... I've tweaked the overlay and I suspect it will be published rapidly since we 're making some modifications to some aspects of the site (and content pushing typically occurs as part of the process).

thanks for your contribution, much appreciated!

**Pull request merged**
